# Generated by Django 5.1.4 on 2024-12-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADHOC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='company_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='company_type',
            new_name='type',
        ),
    ]
