# Generated by Django 5.1.4 on 2024-12-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADHOC', '0003_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('manager_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('company_size', models.CharField(max_length=100)),
                ('company_description', models.TextField()),
                ('company_type', models.CharField(max_length=100)),
            ],
        ),
    ]
