# Generated by Django 5.1.4 on 2024-12-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ADHOC', '0007_alter_organizationprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='organizationprofile',
            name='user',
        ),
    ]
