# Generated by Django 5.1.4 on 2024-12-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADHOC', '0008_remove_organizationprofile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
